import type { WCAGPrinciple } from '@/shared/types/accessibility.js';
import type { LighthouseAuditMapping } from './lighthouse.type.js';

export const PRINCIPLE_MAP: Record<string, WCAGPrinciple> = {
  '1': 'perceivable',
  '2': 'operable',
  '3': 'understandable',
  '4': 'robust',
};

export const AUDIT_WCAG_MAP: Record<string, Omit<LighthouseAuditMapping, 'auditId' | 'title'>> = {
  'color-contrast': { wcagCriterion: '1.4.3', wcagLevel: 'AA', wcagPrinciple: 'perceivable' },
  'image-alt': { wcagCriterion: '1.1.1', wcagLevel: 'A', wcagPrinciple: 'perceivable' },
  'input-image-alt': { wcagCriterion: '1.1.1', wcagLevel: 'A', wcagPrinciple: 'perceivable' },
  'area-alt': { wcagCriterion: '1.1.1', wcagLevel: 'A', wcagPrinciple: 'perceivable' },
  'object-alt': { wcagCriterion: '1.1.1', wcagLevel: 'A', wcagPrinciple: 'perceivable' },
  'document-title': { wcagCriterion: '2.4.2', wcagLevel: 'A', wcagPrinciple: 'operable' },
  'html-has-lang': { wcagCriterion: '3.1.1', wcagLevel: 'A', wcagPrinciple: 'understandable' },
  'html-lang-valid': { wcagCriterion: '3.1.1', wcagLevel: 'A', wcagPrinciple: 'understandable' },
  'valid-lang': { wcagCriterion: '3.1.2', wcagLevel: 'AA', wcagPrinciple: 'understandable' },
  'meta-viewport': { wcagCriterion: '1.4.4', wcagLevel: 'AA', wcagPrinciple: 'perceivable' },
  'meta-refresh': { wcagCriterion: '2.2.1', wcagLevel: 'A', wcagPrinciple: 'operable' },
  'bypass': { wcagCriterion: '2.4.1', wcagLevel: 'A', wcagPrinciple: 'operable' },
  'link-name': { wcagCriterion: '2.4.4', wcagLevel: 'A', wcagPrinciple: 'operable' },
  'button-name': { wcagCriterion: '4.1.2', wcagLevel: 'A', wcagPrinciple: 'robust' },
  'frame-title': { wcagCriterion: '4.1.2', wcagLevel: 'A', wcagPrinciple: 'robust' },
  'label': { wcagCriterion: '1.3.1', wcagLevel: 'A', wcagPrinciple: 'perceivable' },
  'form-field-multiple-labels': { wcagCriterion: '1.3.1', wcagLevel: 'A', wcagPrinciple: 'perceivable' },
  'list': { wcagCriterion: '1.3.1', wcagLevel: 'A', wcagPrinciple: 'perceivable' },
  'listitem': { wcagCriterion: '1.3.1', wcagLevel: 'A', wcagPrinciple: 'perceivable' },
  'definition-list': { wcagCriterion: '1.3.1', wcagLevel: 'A', wcagPrinciple: 'perceivable' },
  'dlitem': { wcagCriterion: '1.3.1', wcagLevel: 'A', wcagPrinciple: 'perceivable' },
  'td-headers-attr': { wcagCriterion: '1.3.1', wcagLevel: 'A', wcagPrinciple: 'perceivable' },
  'th-has-data-cells': { wcagCriterion: '1.3.1', wcagLevel: 'A', wcagPrinciple: 'perceivable' },
  'heading-order': { wcagCriterion: '1.3.1', wcagLevel: 'A', wcagPrinciple: 'perceivable' },
  'tabindex': { wcagCriterion: '2.4.3', wcagLevel: 'A', wcagPrinciple: 'operable' },
  'accesskeys': { wcagCriterion: '2.4.1', wcagLevel: 'A', wcagPrinciple: 'operable' },
  'duplicate-id-active': { wcagCriterion: '4.1.1', wcagLevel: 'A', wcagPrinciple: 'robust' },
  'duplicate-id-aria': { wcagCriterion: '4.1.1', wcagLevel: 'A', wcagPrinciple: 'robust' },
  'aria-allowed-attr': { wcagCriterion: '4.1.2', wcagLevel: 'A', wcagPrinciple: 'robust' },
  'aria-required-attr': { wcagCriterion: '4.1.2', wcagLevel: 'A', wcagPrinciple: 'robust' },
  'aria-required-children': { wcagCriterion: '4.1.2', wcagLevel: 'A', wcagPrinciple: 'robust' },
  'aria-required-parent': { wcagCriterion: '4.1.2', wcagLevel: 'A', wcagPrinciple: 'robust' },
  'aria-roles': { wcagCriterion: '4.1.2', wcagLevel: 'A', wcagPrinciple: 'robust' },
  'aria-valid-attr': { wcagCriterion: '4.1.2', wcagLevel: 'A', wcagPrinciple: 'robust' },
  'aria-valid-attr-value': { wcagCriterion: '4.1.2', wcagLevel: 'A', wcagPrinciple: 'robust' },
  'aria-hidden-body': { wcagCriterion: '4.1.2', wcagLevel: 'A', wcagPrinciple: 'robust' },
  'aria-hidden-focus': { wcagCriterion: '4.1.2', wcagLevel: 'A', wcagPrinciple: 'robust' },
  'font-size': { wcagCriterion: '1.4.4', wcagLevel: 'AA', wcagPrinciple: 'perceivable' },
  'tap-targets': { wcagCriterion: '2.5.5', wcagLevel: 'AAA', wcagPrinciple: 'operable' },
  'video-caption': { wcagCriterion: '1.2.2', wcagLevel: 'A', wcagPrinciple: 'perceivable' },
  'video-description': { wcagCriterion: '1.2.5', wcagLevel: 'AA', wcagPrinciple: 'perceivable' },
};
